sudo: required
services:
  - docker

before_install:
  - docker build -t brightshark/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brightshark/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-435760480160'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true

